typography_spectrum: 0.4819797279778868
color:
  brandStrength: 0.11012381664477289
  lightness: 0.6445353352464736
  saturation: 0.9287380785681307
  rhythmicContrast: 0.11063448037020862
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.08027782570570707
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bdaf57ae-c5f0-4514-a628-f939ad273fff.png
name: Comunit√† Cattolica Italiana
navigation:
  - name: Festa di Maria SS. delle Grazie 17/18 settembre 2016
    id: ad064481-071e-4ae9-9b4b-e3c6f927146c
    type: content
title: Sito ufficiale
description: in fase di costruzione
