typography_spectrum: 0.9404255
color:
  brandStrength: 1
  saturation: 0.4553191
  brandColors:
    - '#F7F2F0'
    - '#B1B431'
    - '#32110D'
    - '#90251A'
    - '#C15D4D'
  lightness: 1
  rhythmicContrast: 0
layout_spectrum: 0.7276596
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bdaf57ae-c5f0-4514-a628-f939ad273fff.png
name: CCI
navigation:
  - name: CP
    id: edf051cd-b1c2-40d0-a76c-970da2fcb900
    type: content
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
title: Comunit√† Cattolica Italiana di Calw
description: Maria SS. delle Grazie
